name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-test-job:
        runs-on: ubuntu-latest
        container:
            image: rancher/dapper:v0.6.0
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock
        steps:
            - name: Add Git
              run: apk add -U git
            - name: Checkout code
              uses: actions/checkout@v4
            - name: current directory
              run: pwd
            - name: see files
              run: ls -la
            - name: dapper ci
              run: dapper ci
            - name: build dapper
              run: dapper build
            - name: build straight
              run: docker build .
